version: '3.8'

services:
  db-server:
    image: mariadb:10.5
    container_name: internal-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - .:/docker-entrypoint-initdb.d 

  web-server:
    # Kita gunakan image yang mendukung instalasi ekstensi saat dijalankan
    image: php:7.4-apache
    container_name: internal-web
    restart: always
    depends_on:
      - db-server
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    # Perintah sakti untuk mengaktifkan mysqli di dalam container
    entrypoint: 
      - sh
      - -c
      - |
        docker-php-ext-install mysqli
        apache2-foreground